//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWebWithWCF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add", ReplyAction="http://tempuri.org/IService1/addResponse")]
        double add(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add", ReplyAction="http://tempuri.org/IService1/addResponse")]
        System.Threading.Tasks.Task<double> addAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sub", ReplyAction="http://tempuri.org/IService1/subResponse")]
        double sub(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sub", ReplyAction="http://tempuri.org/IService1/subResponse")]
        System.Threading.Tasks.Task<double> subAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/multipli", ReplyAction="http://tempuri.org/IService1/multipliResponse")]
        double multipli(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/multipli", ReplyAction="http://tempuri.org/IService1/multipliResponse")]
        System.Threading.Tasks.Task<double> multipliAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/devide", ReplyAction="http://tempuri.org/IService1/devideResponse")]
        double devide(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/devide", ReplyAction="http://tempuri.org/IService1/devideResponse")]
        System.Threading.Tasks.Task<double> devideAsync(double a, double b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FirstWebWithWCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FirstWebWithWCF.ServiceReference1.IService1>, FirstWebWithWCF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double add(double a, double b) {
            return base.Channel.add(a, b);
        }
        
        public System.Threading.Tasks.Task<double> addAsync(double a, double b) {
            return base.Channel.addAsync(a, b);
        }
        
        public double sub(double a, double b) {
            return base.Channel.sub(a, b);
        }
        
        public System.Threading.Tasks.Task<double> subAsync(double a, double b) {
            return base.Channel.subAsync(a, b);
        }
        
        public double multipli(double a, double b) {
            return base.Channel.multipli(a, b);
        }
        
        public System.Threading.Tasks.Task<double> multipliAsync(double a, double b) {
            return base.Channel.multipliAsync(a, b);
        }
        
        public double devide(double a, double b) {
            return base.Channel.devide(a, b);
        }
        
        public System.Threading.Tasks.Task<double> devideAsync(double a, double b) {
            return base.Channel.devideAsync(a, b);
        }
    }
}
